"""
BranchExecutor — handles Condition nodes (execution.kind = 'branch').

The Condition node evaluates a predicate against upstream data and routes
execution to either the 'true' or 'false' branch.

Phase 6 scope:
  The condition node has a 'condition' field (from the Condition node spec)
  that contains a simple Python expression string generated by AI. In Phase 6,
  we evaluate it safely. The AI-generated code path (Phase 7) will replace this,
  but the routing and branch-marking logic here is the permanent architecture.

Predicate evaluation:
  The condition node's data has a 'condition' field (e.g. "value > 0.7").
  The upstream value connected to the 'input' handle is available as 'value'
  in the evaluation namespace. We also expose 'data' as an alias.

  We use a restricted eval() — not exec(), no builtins except a safe whitelist.
  This is NOT a production sandbox (that's Phase 7 with the Script executor's
  sandbox), but it's safe enough for the simple predicates the Condition node
  generates (comparisons, membership tests, string methods).

Branch marking (the critical architectural piece):
  After evaluating, the executor marks all nodes exclusively reachable through
  the inactive branch as "skipped". The algorithm is documented in plan.md.

  Key invariant: a node is skipped only if ALL its incoming paths go through
  the inactive branch. Convergence nodes (both branches re-join) are NOT skipped.
  The iterative pruning loop in _compute_skipped_nodes enforces this.
"""
from __future__ import annotations

from engine.context import ExecutionContext
from engine.executors.base import ExecutorBase


# Safe builtins for predicate evaluation
_SAFE_BUILTINS = {
    "abs": abs, "all": all, "any": any, "bool": bool, "dict": dict,
    "float": float, "int": int, "isinstance": isinstance, "len": len,
    "list": list, "max": max, "min": min, "round": round, "set": set,
    "str": str, "sum": sum, "tuple": tuple, "type": type,
    "True": True, "False": False, "None": None,
}


def _eval_condition(expression: str, value: object) -> bool:
    """
    Safely evaluates a condition expression string against a value.

    The expression is evaluated in a namespace where:
      value — the upstream node's output (primary variable)
      data  — alias for value (for dict-typed inputs)

    Returns the truthiness of the result.
    Raises ValueError if the expression is empty or evaluation fails.
    """
    if not expression or not expression.strip():
        raise ValueError("Condition expression is empty — check the Condition node's configuration")

    namespace = {
        "__builtins__": _SAFE_BUILTINS,
        "value": value,
        "data": value,
    }

    # If value is a dict, also expose its keys directly
    if isinstance(value, dict):
        namespace.update(value)

    try:
        result = eval(expression.strip(), namespace)  # noqa: S307
    except Exception as exc:
        raise ValueError(f"Condition evaluation failed: {exc!r} — expression: {expression!r}") from exc

    return bool(result)


def _compute_skipped_nodes(
    condition_node_id: str,
    inactive_handle_id: str,
    edges: list[dict],
    all_node_ids: set[str],
) -> set[str]:
    """
    Returns the set of node IDs that should be skipped because they are
    exclusively reachable through the inactive branch.

    Algorithm: BFS from inactive handle targets, then iteratively remove
    nodes that have any incoming parent outside the candidate skip set.
    This correctly handles diamond convergence patterns.

    Args:
        condition_node_id: The condition node's ID
        inactive_handle_id: The full handle key of the inactive output
                            (e.g. "cond-1-false" if condition=True)
        edges: All edges in the graph
        all_node_ids: All node IDs in the graph (for validation)
    """
    # Step 1: BFS from the inactive handle's direct targets
    inactive_edge_targets = {
        e["target"]
        for e in edges
        if e.get("sourceHandle") == inactive_handle_id
        and e.get("target") in all_node_ids
    }

    if not inactive_edge_targets:
        return set()  # inactive branch has no targets — nothing to skip

    # Build full adjacency for BFS
    adjacency: dict[str, list[str]] = {n: [] for n in all_node_ids}
    for e in edges:
        src, tgt = e.get("source"), e.get("target")
        if src in adjacency and tgt in all_node_ids:
            adjacency[src].append(tgt)

    # Step 2: BFS — collect all nodes reachable from the inactive seed set
    candidate_skip: set[str] = set()
    queue = list(inactive_edge_targets)
    while queue:
        current = queue.pop(0)
        if current in candidate_skip:
            continue
        candidate_skip.add(current)
        for neighbour in adjacency.get(current, []):
            if neighbour not in candidate_skip:
                queue.append(neighbour)

    # Step 3: Build reverse adjacency (who points TO each node)
    reverse_adj: dict[str, set[str]] = {n: set() for n in all_node_ids}
    for e in edges:
        src, tgt = e.get("source"), e.get("target")
        if src in all_node_ids and tgt in all_node_ids:
            reverse_adj[tgt].add(src)

    # Step 4: Iteratively remove nodes that have any incoming edge from OUTSIDE
    # the candidate skip set (excluding the condition node's inactive output itself).
    # Repeat until stable — un-skipping a node may expose its descendants.
    changed = True
    while changed:
        changed = False
        for node_id in list(candidate_skip):
            parents = reverse_adj.get(node_id, set())
            # A parent is "active" if it is not itself a candidate for skipping
            # and it's not the condition node (condition node's active output stays live)
            active_parents = parents - candidate_skip - {condition_node_id}
            if active_parents:
                # This node has at least one active incoming path → NOT exclusively
                # reachable via the inactive branch → do not skip it
                candidate_skip.discard(node_id)
                changed = True

    return candidate_skip


class BranchExecutor(ExecutorBase):
    """
    Evaluates the condition expression and marks inactive branch nodes as skipped.

    Node data fields (from condition-spec.js):
      condition (str): the predicate expression, e.g. "value > 0.7"

    Input handles:
      input — the value to evaluate the condition against

    Output handles:
      true  — fires when condition is truthy
      false — fires when condition is falsy

    The executor does NOT route data — the graph topology does that.
    It only marks inactive nodes as skipped in ctx.skipped_nodes.
    The output dict records which branch fired (for the SSE event and frontend).
    """

    async def execute(self, node: dict, ctx: ExecutionContext) -> dict:
        node_id = node["id"]
        data = ctx.get_node_data(node_id)

        condition_expr = data.get("condition", "")
        input_value = ctx.get_input(node_id, "input")

        # Evaluate the predicate
        result = _eval_condition(condition_expr, input_value)
        active_branch = "true" if result else "false"
        inactive_branch = "false" if result else "true"

        # Mark exclusively-inactive-branch nodes as skipped
        inactive_handle_key = f"{node_id}-{inactive_branch}"
        all_node_ids = {n["id"] for n in ctx.graph.get("nodes", [])}
        edges = ctx.graph.get("edges", [])

        skipped = _compute_skipped_nodes(
            condition_node_id=node_id,
            inactive_handle_id=inactive_handle_key,
            edges=edges,
            all_node_ids=all_node_ids,
        )
        ctx.skipped_nodes.update(skipped)

        return {
            "result": result,
            active_branch: input_value,   # the active branch output carries the input value through
            "dataType": "boolean",
            "_branch_fired": active_branch,  # internal metadata for the engine's event emission
        }
